Repository price-offer/offer-design-system, pull requests merged in 2022-12, with the labels that each got.

#106 release: v0.1.3 upgrade
  package.json
  packages/react/package.json
  packages/react/src/styles/StyleProvider.tsx
  packages/react/vite.config.ts
Labels: release

#109 fix: 모달 컴포넌트 스크롤 이슈 수정
  packages/react/src/components/Modal/index.tsx
  yarn.lock
Labels: fix

#110 release: v0.1.4 upgrade
  package.json
  packages/react/package.json
Labels: release

#111 release: v0.1.5 upgrade
  packages/chromatic/tsconfig.json
  packages/react/tsconfig.json
  packages/react/tsconfig.path.json
  tsconfig.base.json
Labels: release

#112 release: v0.1.6 upgrade
  packages/react/src/components/ImageModal/index.tsx
  packages/react/src/components/Modal/Modal.stories.tsx
  packages/react/src/components/Modal/index.tsx
Labels: release

#113 release: update v0.1.6
  package.json
  packages/react/package.json
Labels: release

#115 feat: Modal props 타입 수정
  packages/react/src/components/Modal/Modal.stories.tsx
  packages/react/src/components/Modal/index.tsx
Labels: feat

#117 config: tsconfig 파일 찾지 못하는 이슈 수정
  packages/chromatic/.storybook/main.js
  packages/chromatic/tsconfig.json
  packages/react/src/components/Avatar/index.tsx
  packages/react/src/components/Badge/index.tsx
  packages/react/src/components/Button/index.tsx
  packages/react/src/components/Carousel/index.tsx
  packages/react/src/components/ChattingBubble/index.tsx
  packages/react/src/components/Icon/index.tsx
  packages/react/src/components/IconButton/index.tsx
  packages/react/src/components/Image/index.tsx
  packages/react/src/components/ImageModal/index.tsx
  packages/react/src/components/ImageUploader/index.tsx
  packages/react/src/components/ImageUploader/uploader/DesktopUploader.tsx
  packages/react/src/components/ImageUploader/uploader/MobileUploader.tsx
  packages/react/src/components/ImageUploader/useImageUploader.ts
  packages/react/src/components/Input/ChattingInput.tsx
  packages/react/src/components/Input/DefaultInput.tsx
  packages/react/src/components/Input/EditInput.tsx
  packages/react/src/components/Input/SearchInput.tsx
  packages/react/src/components/Modal/index.tsx
  packages/react/src/components/Radio/index.tsx
  packages/react/src/components/SelectBox/index.tsx
  packages/react/src/components/Text/Text.stories.tsx
  packages/react/src/components/Text/index.tsx
  packages/react/src/components/Textarea/index.tsx
  packages/react/src/components/ToggleButton/index.tsx
  packages/react/src/styles/global.tsx
  packages/react/src/styles/themes/border.ts
  packages/react/src/styles/themes/colors.ts
  packages/react/src/styles/themes/fonts.ts
  packages/react/src/styles/themes/mediaQuery.ts
  packages/react/src/styles/themes/radius.ts
  packages/react/src/styles/themes/zIndex.ts
  packages/react/tsconfig.json
  tsconfig.json
Labels: config
