Repository price-offer/offer-design-system, pull requests merged in 2022-10, with the labels that each got.

#53 chore: storybook logo,favicon 변경
  .storybook/manager-head.html
  .storybook/manager.js
  .storybook/theme.js
Labels: chore

#61 fix: husky 동작 이슈 디버깅, icon 컴포넌트 수정 사항 적용
  .husky/pre-commit
  package.json
  src/components/Button/index.tsx
  src/components/Carousel/index.tsx
Labels: config, fix

#38 feat: 디자인 시스템 2차 작업 (Image, Avatar, ImageUploader, SelectBox)
  package.json
  src/components/Avatar/Avatar.stories.tsx
  src/components/Avatar/index.tsx
  src/components/Image/Image.stories.tsx
  src/components/Image/index.tsx
  src/components/ImageUploader/ImageUploader.stories.tsx
  src/components/ImageUploader/index.tsx
  src/components/ImageUploader/uploader/DesktopUploader.tsx
  src/components/ImageUploader/uploader/MobileUploader.tsx
  src/components/ImageUploader/uploader/index.ts
  src/components/ImageUploader/useImageUploader.ts
  src/components/SelectBox/SelectBox.stories.tsx
  src/components/SelectBox/index.tsx
  src/components/index.ts
  src/constants/index.ts
  src/constants/service.ts
  src/hooks/index.ts
  src/hooks/useClose.ts
  src/hooks/useImage.ts
  yarn.lock
Labels: feat, waiting Code Review

#37 feat: 2차 디자인 시스템 개발 (radioButton, ChattingBubble, TextArea)
  src/components/ChattingBubble/ChattingBubble.stories.tsx
  src/components/ChattingBubble/index.tsx
  src/components/Radio/Radio.stories.tsx
  src/components/Radio/index.tsx
  src/components/Textarea/Textarea.stories.tsx
  src/components/Textarea/index.tsx
  src/styles/themes/fonts.ts
Labels: feat, in progress Code Review

#63 fix: Image Component Background-color 오류 디버깅 및 radio onChange 오류 디버깅
  src/components/Image/index.tsx
  src/components/Radio/Radio.stories.tsx
Labels: fix

#35 feat: 2차 디자인 시스템 개발 (Input, IconButton, Modal, ImageModal)
  src/components/IconButton/IconButton.stories.tsx
  src/components/IconButton/index.tsx
  src/components/ImageModal/ImageModal.stories.tsx
  src/components/ImageModal/index.tsx
  src/components/Input/ChattingInput.tsx
  src/components/Input/DefaultInput.tsx
  src/components/Input/EditInput.tsx
  src/components/Input/Input.stories.tsx
  src/components/Input/SearchInput.tsx
  src/components/Input/index.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/index.tsx
  src/components/ToggleButton/ToggleButton.stories.tsx
  src/components/ToggleButton/index.tsx
  src/components/index.ts
  src/constants/service.ts
  src/hooks/index.ts
  src/hooks/useClickAway.ts
  src/styles/themes/zIndex.ts
  src/utils/format.ts
  src/utils/validation.ts
Labels: feat, waiting Code Review

#71 config: declare type, type 이슈 수정, Component export 순서 변경
  src/components/ImageUploader/index.tsx
  src/components/ImageUploader/useImageUploader.ts
  src/components/SelectBox/index.tsx
  src/components/index.ts
  src/types/declare.d.ts
  src/types/index.ts
  src/types/offer.d.ts
  src/types/theme.d.ts
  tsconfig.json
Labels: config

#75 config: 내부 depth에 있는 파일의 경우, lint가 적용되지 않는 현상 해결
  package.json
Labels: config

#73 refactor: props명 통일, Button 컴포넌트 오타 수정
  package.json
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/index.tsx
  src/components/Button/Button.stories.tsx
  src/components/Button/index.tsx
  src/components/ChattingBubble/ChattingBubble.stories.tsx
  src/components/ChattingBubble/index.tsx
  src/components/Divider/Divider.stories.tsx
  src/components/Divider/index.tsx
  src/components/IconButton/IconButton.stories.tsx
  src/components/IconButton/index.tsx
  src/components/ImageModal/index.tsx
  src/components/ImageUploader/ImageUploader.stories.tsx
  src/components/ImageUploader/index.tsx
  src/components/ImageUploader/uploader/DesktopUploader.tsx
  src/components/ImageUploader/uploader/MobileUploader.tsx
  src/components/ImageUploader/useImageUploader.ts
  src/components/Input/ChattingInput.tsx
  src/components/Input/Input.stories.tsx
  src/components/Input/index.tsx
  src/components/Modal/index.tsx
  src/components/SelectBox/SelectBox.stories.tsx
  src/components/SelectBox/index.tsx
  src/components/Text/Text.stories.tsx
  src/components/Text/index.tsx
  src/components/ToggleButton/ToggleButton.stories.tsx
  src/components/ToggleButton/index.tsx
  src/types/offer.d.ts
Labels: refactor

#80 config: lint 설정 커밋 cherry pick
  package.json
Labels: config

#85 design: ImageModal 디자인 수정
  src/components/ImageModal/index.tsx
Labels: design

#88 docs: readme 설정 및 패키지 버전 업
  README.md
  package.json
  packages/react/package.json
Labels: docs

#92 chore: 불필요한 명령어 제거
  packages/react/package.json
Labels: chore

#94 fix: carousel components export로 변경, images 디렉토리 제거
  package.json
  packages/react/package.json
  packages/react/public/images/category_appliance.png
  packages/react/public/images/category_appliance_pc.png
  packages/react/public/images/category_book.png
  packages/react/public/images/category_book_pc.png
  packages/react/public/images/category_car.png
  packages/react/public/images/category_car_pc.png
  packages/react/public/images/category_digitaldevice.png
  packages/react/public/images/category_digitaldevice_pc.png
  packages/react/public/images/category_ect.png
  packages/react/public/images/category_ect_pc.png
  packages/react/public/images/category_furniture.png
  packages/react/public/images/category_furniture_pc.png
  packages/react/public/images/category_game.png
  packages/react/public/images/category_game_pc.png
  packages/react/public/images/category_mangoods.png
  packages/react/public/images/category_mangoods_pc.png
  packages/react/public/images/category_more.png
  packages/react/public/images/category_more_pc.png
  packages/react/public/images/category_petgoods.png
  packages/react/public/images/category_petgoods_pc.png
  packages/react/public/images/category_sports.png
  packages/react/public/images/category_sports_pc.png
  packages/react/public/images/category_toy.png
  packages/react/public/images/category_toy_pc.png
  packages/react/public/images/category_womangoods.png
  packages/react/public/images/category_womangoods_pc.png
  packages/react/src/components/Carousel/Carousel.stories.tsx
  packages/react/src/components/Carousel/index.tsx
  packages/react/src/constants/images.ts
  packages/react/src/constants/index.ts
  packages/react/src/types/declare.d.ts
Labels: fix
