Repository price-offer/offer-design-system, pull requests merged in 2022-09, with the labels that each got.

#13 feat: reset css, global font face 적용, 기본 구조 제거
  .storybook/preview.jsx
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Regular.woff
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/styles/font.ts
  src/styles/global.tsx
  src/styles/index.ts
  src/styles/reset.ts
  src/styles/themes/border.ts
  src/styles/themes/colors.ts
  src/styles/themes/fonts.ts
  src/styles/themes/index.ts
  src/styles/themes/mediaQuery.ts
  src/styles/themes/radius.ts
  src/styles/themes/theme.ts
  src/styles/themes/zIndex.ts
  src/types/emotion.d.ts
  tsconfig.path.json
  yarn.lock
Labels: feat

#19 config: chromatic font face 적용
  .storybook/main.js
  src/styles/font.ts
Labels: config

#22 chore: global font face regular로 설정
  src/styles/global.tsx
Labels: chore

#24 chore: font face 설정 오류 개선, 기본값 regular로 재지정
  src/styles/font.ts
  src/styles/global.tsx
  src/styles/themes/fonts.ts
Labels: chore

#27 config: eslint rule 추가 및 lint 디버깅
  .eslintrc.json
  package.json
  src/components/Test/index.tsx
  yarn.lock
Labels: config

#29 feat: theme font 구조 변경
  src/styles/themes/fonts.ts
Labels: feat

#9 feat: 디자인 시스템 1차 작업 사항 이관 (Divider, Badge)
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/index.tsx
  src/components/Divider/Divider.stories.tsx
  src/components/Divider/index.tsx
  src/components/index.ts
Labels: feat

#17 feat: 1차 디자인 시스템 개발 (Button, Text)
  package.json
  src/components/Button/Button.stories.tsx
  src/components/Button/index.tsx
  src/components/Text/Text.stories.tsx
  src/components/Text/index.tsx
  src/styles/themes/fonts.ts
  src/types/theme.d.ts
  yarn.lock
Labels: feat

#16 feat: 디자인 시스템 1차 작업 사항 이관 (Carousel)
  src/components/Carousel/Carousel.stories.tsx
  src/components/Carousel/index.tsx
  src/hooks/useMediaQuery.ts
  src/styles/themes/mediaQuery.ts
Labels: feat

#34 chore: 컨벤션 통일, 이미지 파일 수정 등
  public/icons/heart_16.svg
  src/components/Badge/Badge.stories.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/Carousel/index.tsx
  src/components/Divider/Divider.stories.tsx
  src/components/Test/Test.stories.tsx
  src/components/Test/index.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/styles/themes/colors.ts
Labels: chore

#40 chore: global font color 추가
  src/styles/global.tsx
Labels: chore

#43 config: eslint 설정 변경
  .eslintrc.json
Labels: config

#45 chore: theme color dim 추가
  src/styles/themes/colors.ts
Labels: chore

#47 chore: font 수정 및 storybook 컨벤션 통일화
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/index.tsx
  src/components/Button/Button.stories.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/Divider/Divider.stories.tsx
  src/components/Text/Text.stories.tsx
  src/styles/themes/fonts.ts
Labels: chore

#49 design: Button 컴포넌트 디자인 및 Storybook control 수정
  src/components/Button/index.tsx
  src/components/Text/Text.stories.tsx
Labels: chore, design

#51 fix: 캐러젤 터치슬라이드 이벤트가 간헐적으로 안되는 현상 수정
  src/components/Carousel/index.tsx
Labels: fix, waiting Code Review
