Repository price-offer/offer-design-system, pull requests merged in 2023-12, with the labels that each got.

#222 fix: 이미지 깨짐 현상 수정
  packages/react/src/components/Image/index.tsx
Labels: fix

#223 release: v0.2.2
  .changeset/wicked-mirrors-trade.md
Labels: release

#224 chore: version packages
  .changeset/wicked-mirrors-trade.md
  packages/react/CHANGELOG.md
  packages/react/package.json
Labels: release

#225 fix: 이미지 미디어쿼리 대응 이슈 해결
  .changeset/eleven-keys-taste.md
  packages/react/src/components/Image/index.tsx
Labels: fix

#228 config: playground에 스타일링을 위한 emotion 패키지 설치
  apps/ods-playground-next/next.config.js
  apps/ods-playground-next/package.json
  apps/ods-playground-react/package.json
Labels: config, feat

#227 fix: 이미지 업로더 컴포넌트 하이드레이션 이슈 디버깅 및 useIsomorphicLayoutEffect 훅 구현
  .changeset/warm-lizards-attack.md
  apps/ods-playground-next/next.config.js
  apps/ods-playground-next/package.json
  apps/ods-playground-react/package.json
  packages/react/src/components/ImageUploader/uploader/MobileUploader.tsx
  packages/react/src/hooks/index.ts
  packages/react/src/hooks/useImage.ts
  packages/react/src/hooks/useIsomorphicLayoutEffect.ts
  packages/react/src/hooks/useMedia.tsx
Labels: fix

#233 fix: ImageUploader 컴포넌트 상태 업데이트 및 전달 데이터 수정
  packages/react/src/components/Icon/index.tsx
  packages/react/src/components/ImageUploader/useImageUploader.ts
  packages/react/src/hooks/useMediaQuery.ts
  yarn.lock
Labels: feat, waiting Code Review

#234 feat: Radio 값 reset 할 수 있도록 수정
  packages/react/src/components/Radio/Default.tsx
  packages/react/src/components/Radio/Input.tsx
Labels: feat, waiting Code Review
