Repository price-offer/offer-design-system, pull requests merged in 2023-01, with the labels that each got.

#120 release: v0.1.9 upgrade
  package.json
  packages/chromatic/.storybook/main.js
  packages/chromatic/tsconfig.json
  packages/chromatic/vite.config.ts
  packages/react/package.json
  packages/react/tsconfig.json
  packages/react/vite.config.ts
Labels: release

#122 design: 버튼 컴포넌트 너비 고정 해제
  packages/react/src/components/Button/Button.stories.tsx
  packages/react/src/components/Button/index.tsx
Labels: design

#123 release: update v0.1.10
  package.json
  packages/react/package.json
Labels: release

#124 release: v0.1.11
  package.json
  packages/react/package.json
Labels: release

#126 fix: Badge 컴포넌트 children 타입 오류 수정
  packages/react/src/components/Badge/index.tsx
  packages/react/src/components/Text/index.tsx
Labels: fix

#127 release: update v0.1.12
  package.json
  packages/react/package.json
Labels: release

#130 fix: Button 컴포넌트 children 타입 오류 수정
  packages/react/src/components/Button/index.tsx
Labels: fix

#131 release: update v0.1.13
  package.json
  packages/react/package.json
Labels: release

#134 feat: theme color객체 수정 및 적용
  packages/react/.eslintrc.json
  packages/react/src/components/Avatar/index.tsx
  packages/react/src/components/Badge/index.tsx
  packages/react/src/components/Button/index.tsx
  packages/react/src/components/Carousel/index.tsx
  packages/react/src/components/ChattingBubble/index.tsx
  packages/react/src/components/Divider/index.tsx
  packages/react/src/components/Icon/Icon.stories.tsx
  packages/react/src/components/Icon/index.tsx
  packages/react/src/components/IconButton/IconButton.stories.tsx
  packages/react/src/components/IconButton/index.tsx
  packages/react/src/components/Image/index.tsx
  packages/react/src/components/ImageModal/index.tsx
  packages/react/src/components/ImageUploader/uploader/DesktopUploader.tsx
  packages/react/src/components/ImageUploader/uploader/MobileUploader.tsx
  packages/react/src/components/Input/ChattingInput.tsx
  packages/react/src/components/Input/DefaultInput.tsx
  packages/react/src/components/Input/EditInput.tsx
  packages/react/src/components/Input/SearchInput.tsx
  packages/react/src/components/Input/index.tsx
  packages/react/src/components/Modal/index.tsx
  packages/react/src/components/Radio/index.tsx
  packages/react/src/components/SelectBox/index.tsx
  packages/react/src/components/Text/index.tsx
  packages/react/src/components/Textarea/index.tsx
  packages/react/src/components/ToggleButton/ToggleButton.stories.tsx
  packages/react/src/styles/global.tsx
  packages/react/src/styles/themes/border.ts
  packages/react/src/styles/themes/colors.ts
  packages/react/src/styles/themes/fonts.ts
  packages/react/src/styles/themes/mediaQuery.ts
  packages/react/src/styles/themes/radius.ts
  packages/react/src/styles/themes/zIndex.ts
  packages/react/src/types/emotion.d.ts
  packages/react/src/types/offer.d.ts
  packages/react/src/utils/format.ts
Labels: feat

#136 release: update v0.1.14
  package.json
  packages/react/package.json
Labels: release

#137 fix: IconButton, Divider 이슈 수정
  packages/react/src/components/Divider/Divider.stories.tsx
  packages/react/src/components/Divider/index.tsx
  packages/react/src/components/Icon/Icon.stories.tsx
  packages/react/src/components/IconButton/IconButton.stories.tsx
  packages/react/src/components/IconButton/index.tsx
  packages/react/src/components/ImageModal/index.tsx
  packages/react/src/components/Input/ChattingInput.tsx
  packages/react/src/components/ToggleButton/ToggleButton.stories.tsx
  packages/react/src/components/ToggleButton/index.tsx
Labels: feat, fix

#139 release: update v0.1.5
  package.json
  packages/react/package.json
Labels: release

#141 feat: color를 prop으로 받는 컴포넌트들 type 좁히기
  packages/react/src/components/Input/EditInput.tsx
  packages/react/src/components/Text/Text.stories.tsx
  packages/react/src/components/Text/index.tsx
  packages/react/src/components/Textarea/index.tsx
Labels: feat

#143 feat: 컴포넌트 사용성을 위한 prop 수정
  packages/react/src/components/Button/Button.stories.tsx
  packages/react/src/components/Button/index.tsx
  packages/react/src/components/IconButton/index.tsx
  packages/react/src/components/ToggleButton/ToggleButton.stories.tsx
  packages/react/src/components/ToggleButton/index.tsx
Labels: feat

#138 refactor: Select Component 구조 변경 및 버그 개선
  packages/react/src/components/SelectBox/SelectBox.stories.tsx
  packages/react/src/components/SelectBox/index.tsx
  packages/react/src/types/offer.d.ts
Labels: refactor

#144 release: update v0.1.16
  package.json
  packages/react/package.json
Labels: release

#148 fix: Badge 컴포넌트 텍스트 색상 적용 안되는 이슈 수정
  packages/react/src/components/Badge/index.tsx
Labels: fix

#151 refactor: SelectBox api 구조에 맞게 변경
  packages/react/src/components/SelectBox/SelectBox.stories.tsx
  packages/react/src/components/SelectBox/index.tsx
  packages/react/src/types/offer.d.ts
Labels: refactor

#154 fix: selectBox 타입 확장 및 불필요한 타입 제거
  packages/react/src/components/SelectBox/SelectBox.stories.tsx
  packages/react/src/components/SelectBox/index.tsx
  packages/react/src/types/offer.d.ts
Labels: fix

#153 design: Text 기본 색상값 제거
  packages/react/src/components/Text/index.tsx
Labels: design

#155 release: release v0.1.18
  package.json
  packages/react/package.json
Labels: release

#156 refactor: Selectbox 타입 이슈로 인해 any로 item 타입 확장, ReactNode관련 타입 재지정
  packages/react/src/components/Badge/index.tsx
  packages/react/src/components/Button/index.tsx
  packages/react/src/components/SelectBox/SelectBox.stories.tsx
  packages/react/src/components/Text/index.tsx
  packages/react/src/types/offer.d.ts
Labels: refactor

#158 fix:캐러젤 이슈대응
  packages/react/src/components/Carousel/index.tsx
  packages/react/src/hooks/useMedia.tsx
Labels: fix

#161 release: update v0.1.19
  package.json
  packages/react/package.json
Labels: release

#162 release:v 0.1.21
  package.json
  packages/react/package.json
Labels: release

#166 fix: 패키지에 없는 컴포넌트 찾기
  packages/react/src/components/CheckBox/index.tsx
  packages/react/src/components/index.ts
  packages/react/src/hooks/index.ts
Labels: fix

#167 release: update v0.1.23
  package.json
  packages/react/package.json
Labels: config

#169 refactor: { code, name }으로 받는 형태에 대한 타입 확장
  packages/react/.eslintrc.json
  packages/react/src/components/CheckBox/hooks/index.ts
  packages/react/src/components/CheckBox/index.tsx
  packages/react/src/components/Radio/index.tsx
  packages/react/src/components/SelectBox/index.tsx
  packages/react/src/types/offer.d.ts
Labels: refactor

#170 release: v0.1.24
  package.json
  packages/react/package.json
Labels: release
