Repository price-offer/offer-design-system, pull requests merged in 2023-10, with the labels that each got.

#193 fix: Icon 컴포넌트 smile 이 비율에 따라 stroke-width 가 유지가 안되고 깨지는 현상 수정
  packages/react/public/icons/smile.svg
Labels: fix, finish Code Review

#185 refactor: Radio 컴포넌트 확장성있게 변경
  packages/react/src/components/Radio/Default.tsx
  packages/react/src/components/Radio/Input.tsx
  packages/react/src/components/Radio/Radio.stories.tsx
  packages/react/src/components/Radio/index.tsx
  packages/react/src/components/Radio/styled.ts
  packages/react/src/components/Radio/types.ts
Labels: refactor, finish Code Review

#194 release: v0.1.26
  package.json
  packages/react/package.json
Labels: release

#198 design: Selectbox width값 변경에 용이하도록 수정
  packages/react/src/components/SelectBox/index.tsx
Labels: design

#199 release: v0.1.27
  package.json
  packages/react/package.json
Labels: release

#201 design: 상위 요소에 의해 사이즈 틀어지는 이슈 수정
  packages/react/src/components/Avatar/index.tsx
  packages/react/src/components/Image/index.tsx
  packages/react/src/components/Radio/Default.tsx
  packages/react/src/components/Radio/Input.tsx
  packages/react/src/components/Radio/Radio.stories.tsx
Labels: design, finish Code Review
