Repository price-offer/offer-design-system, pull requests merged in 2024-01, with the labels that each got.

#241 design: Selectbox 컴포넌트 dark일 때 스타일 이슈 수정
  .changeset/three-cobras-agree.md
  packages/react/src/components/SelectBox/index.tsx
Labels: design

#246 design: 뱃지 컴포넌트 높이값 틀어지지 않도록 수정
  packages/react/src/components/Badge/index.tsx
Labels: design

#245 feat: ImageUploader 컴포넌트 상위에서 내려준 data와 싱크 맞추기
  packages/react/src/components/ImageUploader/useImageUploader.ts
Labels: feat, waiting Code Review

#247 Release/v0.2.8
  .changeset/cyan-dots-dress.md
  packages/react/src/components/Badge/index.tsx
  packages/react/src/components/ImageUploader/useImageUploader.ts
Labels: release

#250 feat: export the useImageUploader hook
  .changeset/eighty-plums-travel.md
  .changeset/light-gorillas-sit.md
  .changeset/ten-ways-fly.md
  packages/react/src/components/ImageUploader/index.tsx
  packages/react/src/components/ImageUploader/uploader/DesktopUploader.tsx
  packages/react/src/components/ImageUploader/uploader/MobileUploader.tsx
  packages/react/src/hooks/index.ts
  packages/react/src/hooks/useImageListUploader.ts
  packages/react/src/hooks/useImageUploader.ts
  packages/react/src/utils/validation.ts
Labels: feat

#253 feat: Carousel, ImageModal 컴포넌트 개선
  .changeset/empty-jeans-greet.md
  packages/react/src/components/Carousel/Carousel.stories.tsx
  packages/react/src/components/Carousel/index.tsx
  packages/react/src/components/ImageModal/ImageModal.stories.tsx
  packages/react/src/components/ImageModal/index.tsx
Labels: feat, waiting Code Review

#256 design: Carousel, ImageModal 디자인 수정
  packages/react/src/components/Carousel/index.tsx
  packages/react/src/components/ImageModal/index.tsx
Labels: design, waiting Code Review

#257 refactor: refactor: Input 컴포넌트 개선
  packages/react/src/components/Input/Chatting.tsx
  packages/react/src/components/Input/Default.tsx
  packages/react/src/components/Input/Edit.tsx
  packages/react/src/components/Input/Input.stories.tsx
  packages/react/src/components/Input/Search.tsx
  packages/react/src/components/Input/index.tsx
Labels: refactor, waiting Code Review

#262 fix: Input.Edit 가격이 아닌 경우도 가능하도록
  .changeset/shiny-cars-attend.md
  packages/react/src/components/Input/Edit.tsx
Labels: feat, waiting Code Review

#264 design: Edit-Input isPrice에 따른 디자인 변화
  .changeset/serious-zoos-retire.md
  packages/react/src/components/Input/Edit.tsx
Labels: design

#266 fix: ImageModal, Carousel 수정
  .changeset/angry-nails-fly.md
  packages/react/src/components/Carousel/index.tsx
  packages/react/src/components/ImageModal/index.tsx
Labels: fix, waiting Code Review
